version: '3'

services:

  builder:
    image: tollsimy/xv6-riscv-vf2:latest
    container_name: xv6-riscv-vf2
    restart: "no"
    working_dir: "/home/user/"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    volumes:
      - ../:/home/user/src