FROM ubuntu:22.04

ENV TZ="Europe/Rome"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG USERNAME=user

RUN apt update && apt install -y --no-install-recommends \
    bash pkg-config ccache sudo wget rsync \
    autoconf automake autotools-dev curl python3 python3-pip \
    libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison \
    flex texinfo gperf libtool patchutils bc zlib1g-dev \
    libexpat-dev ninja-build git cmake libglib2.0-dev

ENV HOME=/home/$USERNAME
ENV USER=$USERNAME

RUN adduser --disabled-password --gecos '' user
RUN adduser user sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

WORKDIR /tmp
RUN wget -O riscv64-elf-toolchain.tar.gz \
    https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.03.01/riscv64-elf-ubuntu-22.04-gcc-nightly-2024.03.01-nightly.tar.gz
RUN tar -xzvf riscv64-elf-toolchain.tar.gz --strip-components 1 && rsync -av . /usr/local/
RUN rm riscv64-elf-toolchain.tar.gz
ENV TOOLPREFIX=/usr/local/bin/riscv64-unknown-elf-

RUN git clone https://github.com/qemu/qemu && \
    cd qemu && git checkout v8.2.2 && \
    ./configure --target-list=riscv64-softmmu && \
    make -j $(nproc) && \
    make install

USER $USER
WORKDIR $HOME